(define (problem solve-gripper)
  (:domain gripper)
  (:objects ra rb b1 b2 b3 b4 l r)
  (:init 
        (room ra)
        (room rb)
        (ball b1)
        (ball b2)
        (ball b3)
        (ball b4)
        (gripper l)
        (gripper r)
        (free l)
        (free r)
        (at-robby ra)
        (at-ball b1 ra)
        (at-ball b2 ra)
        (at-ball b3 ra)
        (at-ball b4 ra)
  )
  (:goal (and (at-ball b1 rb)
              (at-ball b2 rb)
              (at-ball b3 rb)
              (at-ball b4 rb)
              ))

)